In [3]:
import pandas as pd
import numpy as np

In [4]:
Tertiary = pd.read_csv("tertiary.csv")

In [5]:
Tertiary.head()
Tertiary.columns

Index(['State', 'City', 'Bars', 'Restaurant', 'Museums', 'Libraries',
       'Pro_sports_team', 'Park_acres_per_1000_residents', 'NumTop200Restau'],
      dtype='object')

In [4]:
from geopy.geocoders import Nominatim


geolocator = Nominatim()

Lat = []
Lon = []
n = len(Tertiary['City'])

Cities = Tertiary['City']
States = Tertiary['State']

for j in range(0, n):
    city = Cities[j]
    state = States[j]
    
    if city == "San Francisco":
        location = geolocator.geocode(94105)
        lat = location.latitude
        lon = location.longitude
        Lat.append(lat)
        Lon.append(lon)

    else:
        location = geolocator.geocode( city + " United States")
        lat = location.latitude
        lon = location.longitude
        Lat.append(lat)
        Lon.append(lon)

    
Tertiary['Lat'] = Lat
Tertiary['Lon'] = Lon

In [5]:
Tertiary.head(10)
Tertiary[Tertiary.index == 0]
tertiary = Tertiary

In [6]:
# Give the rank of the city for each factor

tertiary['Bar_Rank'] = tertiary['Bars'].rank(ascending = 0)
tertiary['Restaurant_Rank'] = tertiary['Restaurant'].rank(ascending = 0)
tertiary['Museums_Rank'] = tertiary['Museums'].rank(ascending = 0)
tertiary['Libraries_Rank'] = tertiary['Libraries'].rank(ascending = 0)
tertiary['Park_Rank'] = tertiary['Park_acres_per_1000_residents'].rank(ascending = 0)
tertiary['TopRes_Rank'] = tertiary['NumTop200Restau'].rank(ascending = 0)

tertiary

,State,City,Bars,Restaurant,Museums,Libraries,Pro_sports_team,Park_acres_per_1000_residents,NumTop200Restau,Lat,Lon,Bar_Rank,Restaurant_Rank,Museums_Rank,Libraries_Rank,Park_Rank,TopRes_Rank
0,Georgia,Atlanta,146.0,1566.0,37.0,37.0,5.0,7.0,3.0,33.749099,-84.390185,21.0,21.0,10.0,14.0,28.0,6.0
1,Texas,Austin,212.0,2135.0,25.0,35.0,0.0,37.0,2.0,30.271129,-97.743700,15.0,12.0,19.0,19.5,4.0,8.5
2,Maryland,Baltimore,243.0,1590.0,45.0,36.0,2.0,8.0,0.0,39.290882,-76.610759,13.0,19.0,9.0,16.0,24.5,21.5
3,Alabama,Birmingham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.520682,-86.802433,NaN,NaN,NaN,NaN,NaN,NaN
4,Massachusetts,Boston,136.0,2064.0,51.0,54.0,3.0,8.0,3.0,42.360482,-71.059568,24.0,14.0,8.0,6.0,24.5,6.0
5,New York,Buffalo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.886717,-78.878392,NaN,NaN,NaN,NaN,NaN,NaN
6,North Carolina,Charlotte,121.0,1685.0,16.0,26.0,3.0,20.0,NaN,35.227087,-80.843127,25.0,16.0,29.0,25.0,12.0,NaN
7,Illinois,Chicago,807.0,6438.0,76.0,99.0,8.0,4.0,19.0,41.875555,-87.624421,2.0,3.0,4.0,4.0,33.0,3.0
8,Ohio,Cincinnati,105.0,600.0,18.0,35.0,2.0,21.0,0.0,39.101454,-84.512460,27.0,32.0,27.5,19.5,11.0,21.5
9,Ohio,Cleveland,204.0,866.0,23.0,51.0,3.0,7.0,0.0,41.505161,-81.693445,17.0,31.0,20.5,9.0,28.0,21.5
10,Ohio,Columbus,249.0,1656.0,13.0,27.0,2.0,14.7,0.0,39.962260,-83.000707,11.5,18.0,31.0,24.0,17.0,21.5
11,Texas,Dallas,249.0,2808.0,26.0,43.0,2.0,23.0,0.0,32.776272,-96.796856,11.5,9.0,18.0,11.0,9.0,21.5
12,Colorado,Denver,207.0,1741.0,33.0,39.0,6.0,10.0,1.0,39.739154,-104.984703,16.0,15.0,12.0,13.0,21.0,12.0
13,Michigan,Detroit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.348664,-83.056737,NaN,NaN,NaN,NaN,NaN,NaN
14,Connecticut,Hartford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.764549,-72.690867,NaN,NaN,NaN,NaN,NaN,NaN
15,Texas,Houston,549.0,5549.0,58.0,63.0,6.0,22.0,1.0,29.758938,-95.367697,3.0,4.0,6.0,5.0,10.0,12.0
16,Indiana,Indianapolis,195.0,1679.0,21.0,35.0,4.0,14.0,0.0,39.768333,-86.158350,18.0,17.0,23.5,19.5,18.0,21.5
17,Florida,Jacksonville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.332184,-81.655651,NaN,NaN,NaN,NaN,NaN,NaN
18,Missouri,Kansas City,113.0,921.0,28.0,19.0,3.0,36.0,0.0,39.084469,-94.563030,26.0,30.0,17.0,29.5,5.5,21.5
19,Nevada,Las Vegas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.166286,-115.149225,NaN,NaN,NaN,NaN,NaN,NaN
20,California,Los Angeles,393.0,8305.0,106.0,108.0,5.0,6.0,15.0,34.054935,-118.244476,6.0,2.0,2.0,2.0,31.0,4.0
21,Kentucky,Louisville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.254238,-85.759407,NaN,NaN,NaN,NaN,NaN,NaN
22,Tennessee,Memphis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.149022,-90.051629,NaN,NaN,NaN,NaN,NaN,NaN
23,Florida,Miami,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.774266,-80.193659,NaN,NaN,NaN,NaN,NaN,NaN
24,Wisconsin,Milwaukee,390.0,947.0,20.0,30.0,2.0,16.0,2.0,43.034993,-87.922497,7.0,29.0,25.5,23.0,16.0,8.5
25,Minnesota,Minneapolis,97.0,969.0,21.0,25.0,4.0,13.0,0.0,44.977300,-93.265469,29.0,28.0,23.5,26.0,19.0,21.5
26,Tennessee,Nashville,138.0,1493.0,30.0,35.0,3.0,18.0,NaN,36.162230,-86.774353,23.0,22.0,14.0,19.5,13.0,NaN
27,Louisiana,New Orleans,284.0,986.0,34.0,20.0,2.0,84.0,3.0,29.949932,-90.070116,10.0,27.0,11.0,28.0,1.0,6.0
28,New York,New York,1220.0,22320.0,356.0,341.0,8.0,5.0,60.0,40.730646,-73.986614,1.0,1.0,1.0,1.0,32.0,1.0
29,Oklahoma,Oklahoma City,102.0,1251.0,29.0,13.0,2.0,39.0,0.0,35.472989,-97.517054,28.0,23.0,15.5,33.0,3.0,21.5
30,Florida,Orlando,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.542123,-81.379047,NaN,NaN,NaN,NaN,NaN,NaN
31,Pennsylvania,Philadelphia,400.0,3821.0,91.0,100.0,5.0,7.0,1.0,39.952399,-75.163590,4.0,5.0,3.0,3.0,28.0,12.0
32,Arizona,Phoenix,179.0,2384.0,22.0,44.0,5.0,28.0,0.0,33.448587,-112.077346,20.0,10.0,22.0,10.0,7.0,21.5
33,Pennsylvania,Pittsburgh,143.0,992.0,23.0,36.0,3.0,10.0,0.0,40.441694,-79.990086,22.0,26.0,20.5,16.0,21.0,21.5
34,Oregon,Portland,313.0,2084.0,20.0,23.0,2.0,25.0,NaN,45.520247,-122.674195,9.0,13.0,25.5,27.0,8.0,NaN
35,Rhode Island,Providence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.823989,-71.412834,NaN,NaN,NaN,NaN,NaN,NaN
36,Virginia,Richmond,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.538509,-77.434280,NaN,NaN,NaN,NaN,NaN,NaN
37,California,Riverside,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.953355,-117.396162,NaN,NaN,NaN,NaN,NaN,NaN
38,New York,Rochester,78.0,502.0,14.0,17.0,3.0,7.0,NaN,43.157285,-77.615214,31.0,33.0,30.0,32.0,28.0,NaN
39,California,Sacramento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.581572,-121.494400,NaN,NaN,NaN,NaN,NaN,NaN
40,Utah,Salt Lake City,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.767013,-111.890431,NaN,NaN,NaN,NaN,NaN,NaN
41,Texas,San Antonio,345.0,2914.0,31.0,36.0,3.0,17.0,0.0,29.424600,-98.495141,8.0,8.0,13.0,16.0,14.5,21.5
42,California,San Diego,189.0,3126.0,53.0,52.0,2.0,36.0,1.0,32.717421,-117.162771,19.0,7.0,7.0,7.5,5.5,12.0
43,California,San Francisco,394.0,3430.0,70.0,52.0,2.0,7.0,20.0,37.788337,-122.397445,5.0,6.0,5.0,7.5,28.0,2.0
44,California,San Jose,68.0,1578.0,12.0,31.0,4.0,17.0,0.0,37.329709,-121.903160,32.0,20.0,32.0,22.0,14.5,21.5
45,Washington,Seattle,219.0,2307.0,29.0,42.0,4.0,9.0,1.0,47.603832,-122.330062,14.0,11.0,15.5,12.0,23.0,12.0
46,Missouri,St. Louis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.627273,-90.197889,NaN,NaN,NaN,NaN,NaN,NaN
47,Florida,Tampa,91.0,1114.0,18.0,19.0,4.0,10.0,0.0,27.947760,-82.458444,30.0,25.0,27.5,29.5,21.0,21.5
48,Virginia,Virginia Beach,24.0,1144.0,10.0,18.0,0.0,68.0,NaN,36.795302,-76.050925,33.0,24.0,33.0,31.0,2.0,NaN
49,District Of Columbia,Washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.894955,-77.036646,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:

# Set the rank of N/A to the (maximum ranking + 1) for this factor 
tertiary['Bar_Rank'].fillna(tertiary['Bar_Rank'].max()+1,inplace=True)
tertiary['Restaurant_Rank'].fillna(tertiary['Restaurant_Rank'].max()+1,inplace=True)
tertiary['Museums_Rank'].fillna(tertiary['Museums_Rank'].max()+1,inplace=True)
tertiary['Libraries_Rank'].fillna(tertiary['Libraries_Rank'].max()+1,inplace=True)
tertiary['Park_Rank'].fillna(tertiary['Park_Rank'].max()+1,inplace=True)
tertiary['TopRes_Rank'].fillna(tertiary['TopRes_Rank'].max()+1,inplace=True)

In [8]:
# Calculat the sum of rankings for each city -- Total_Rank 
tertiary['Total_Rank'] = (tertiary['Bar_Rank']+tertiary['Restaurant_Rank']+tertiary['Museums_Rank']+tertiary['Libraries_Rank']+tertiary['Park_Rank']+tertiary['TopRes_Rank'])

# Rank the cities based on Total_Rank, the smallest number comes first -- Final_Rank
tertiary['Final_Rank'] = tertiary['Total_Rank'].rank(ascending = 1)

# Set the Final_Rank to be integers
tertiary['Final_Rank'] = tertiary['Final_Rank'].astype(int)

# Set reverse of Final_Rank to make plotting easier 
# (smaller ranking number will be projected to a bigger size)
tertiary['Reverse_Rank'] = 51 - tertiary['Final_Rank']

In [9]:
tertiary.head()

,State,City,Bars,Restaurant,Museums,Libraries,Pro_sports_team,Park_acres_per_1000_residents,NumTop200Restau,Lat,Lon,Bar_Rank,Restaurant_Rank,Museums_Rank,Libraries_Rank,Park_Rank,TopRes_Rank,Total_Rank,Final_Rank,Reverse_Rank
0,Georgia,Atlanta,146.0,1566.0,37.0,37.0,5.0,7.0,3.0,33.749099,-84.390185,21.0,21.0,10.0,14.0,28.0,6.0,100.0,16,35
1,Texas,Austin,212.0,2135.0,25.0,35.0,0.0,37.0,2.0,30.271129,-97.743700,15.0,12.0,19.0,19.5,4.0,8.5,78.0,8,43
2,Maryland,Baltimore,243.0,1590.0,45.0,36.0,2.0,8.0,0.0,39.290882,-76.610759,13.0,19.0,9.0,16.0,24.5,21.5,103.0,17,34
3,Alabama,Birmingham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.520682,-86.802433,34.0,34.0,34.0,34.0,34.0,22.5,192.5,42,9
4,Massachusetts,Boston,136.0,2064.0,51.0,54.0,3.0,8.0,3.0,42.360482,-71.059568,24.0,14.0,8.0,6.0,24.5,6.0,82.5,11,40

In [10]:
tertiary = tertiary.sort_values('Final_Rank', ascending = 1)
tertiary.head(10)

,State,City,Bars,Restaurant,Museums,Libraries,Pro_sports_team,Park_acres_per_1000_residents,NumTop200Restau,Lat,Lon,Bar_Rank,Restaurant_Rank,Museums_Rank,Libraries_Rank,Park_Rank,TopRes_Rank,Total_Rank,Final_Rank,Reverse_Rank
28,New York,New York,1220.0,22320.0,356.0,341.0,8.0,5.0,60.0,40.730646,-73.986614,1.0,1.0,1.0,1.0,32.0,1.0,37.0,1,50
15,Texas,Houston,549.0,5549.0,58.0,63.0,6.0,22.0,1.0,29.758938,-95.367697,3.0,4.0,6.0,5.0,10.0,12.0,40.0,2,49
20,California,Los Angeles,393.0,8305.0,106.0,108.0,5.0,6.0,15.0,34.054935,-118.244476,6.0,2.0,2.0,2.0,31.0,4.0,47.0,3,48
7,Illinois,Chicago,807.0,6438.0,76.0,99.0,8.0,4.0,19.0,41.875555,-87.624421,2.0,3.0,4.0,4.0,33.0,3.0,49.0,4,47
43,California,San Francisco,394.0,3430.0,70.0,52.0,2.0,7.0,20.0,37.788337,-122.397445,5.0,6.0,5.0,7.5,28.0,2.0,53.5,5,46
31,Pennsylvania,Philadelphia,400.0,3821.0,91.0,100.0,5.0,7.0,1.0,39.952399,-75.163590,4.0,5.0,3.0,3.0,28.0,12.0,55.0,6,45
42,California,San Diego,189.0,3126.0,53.0,52.0,2.0,36.0,1.0,32.717421,-117.162771,19.0,7.0,7.0,7.5,5.5,12.0,58.0,7,44
1,Texas,Austin,212.0,2135.0,25.0,35.0,0.0,37.0,2.0,30.271129,-97.743700,15.0,12.0,19.0,19.5,4.0,8.5,78.0,8,43
11,Texas,Dallas,249.0,2808.0,26.0,43.0,2.0,23.0,0.0,32.776272,-96.796856,11.5,9.0,18.0,11.0,9.0,21.5,80.0,9,42
41,Texas,San Antonio,345.0,2914.0,31.0,36.0,3.0,17.0,0.0,29.424600,-98.495141,8.0,8.0,13.0,16.0,14.5,21.5,81.0,10,41

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

In [3]:

Top = tertiary[['Reverse_Rank','City','State','Bar_Rank','Restaurant_Rank',
                'Museums_Rank','Libraries_Rank','Park_Rank','TopRes_Rank',
                'Final_Rank','Lat','Lon' ]]
Top

NameError: name 'tertiary' is not defined

In [6]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

In [44]:
!pip install plotly

Requirement already satisfied: plotly in /anaconda/lib/python3.6/site-packages
Requirement already satisfied: six in /anaconda/lib/python3.6/site-packages (from plotly)
Requirement already satisfied: nbformat>=4.2 in /anaconda/lib/python3.6/site-packages (from plotly)
Requirement already satisfied: requests in /anaconda/lib/python3.6/site-packages (from plotly)
Requirement already satisfied: decorator>=4.0.6 in /anaconda/lib/python3.6/site-packages (from plotly)
Requirement already satisfied: pytz in /anaconda/lib/python3.6/site-packages (from plotly)

In [16]:
import plotly
import plotly.plotly as py
import pandas as pd

df = Top
#df.head()

df['text'] = df['City'] + '<br># Final Rank ' + (df['Final_Rank']).astype(str)+\
'<br># Bars Rank ' + (df['Bar_Rank']).astype(str)+ '<br># Restaurant Rank '+\
(df['Restaurant_Rank']).astype(str)+'<br># Museum Rank ' + (df['Museums_Rank']).astype(str)+'<br># Libraries Rank ' +\
(df['Libraries_Rank']).astype(str)
limits = [(0,10),(10,20),(20,30),(30,40),(40,50)]
colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)","rgb(255,133,27)","lightgrey"]
cities = []


for i in range(len(limits)):
    lim = limits[i]
    df_sub = df[lim[0]:lim[1]]
    city = dict(
        type = 'scattergeo',
        locationmode = 'USA-states',
        lon = df_sub['Lon'],
        lat = df_sub['Lat'],
        text = df_sub['text'],
        
        
        marker = dict(
            size = df_sub['Reverse_Rank']*15,
            color = colors[i],
            line = dict(width=0.5, color='rgb(40,40,40)'),
            sizemode = 'area'
        ),
        name = '{0} - {1}'.format(lim[0],lim[1]) )
    cities.append(city)

layout = dict(
        title = 'USA City Entertainment Ranking<br>(Click legend to toggle traces)',
        showlegend = True,
        geo = dict(
            scope='usa',
            projection=dict( type='albers usa' ),
            showland = True,
            landcolor = 'rgb(216, 217, 218)',
            subunitwidth=1,
            countrywidth=1,
            subunitcolor="rgb(255, 255, 255)",
            countrycolor="rgb(255, 255, 255)"
        ),
    )

fig = dict( data=cities, layout=layout )
plotly.offline.plot( fig, validate=False, filename='d3-bubble-map-populations.html' )

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

'file:///Users/EmilyDelluque/Desktop/UW/Academic/cse583/GeoGraph/d3-bubble-map-populations.html'

In [7]:
Top = pd.read_csv("Top.csv")
Top

,Unnamed: 0,Reverse_Rank,City,State,Bar_Rank,Restaurant_Rank,Museums_Rank,Libraries_Rank,Park_Rank,TopRes_Rank,Final_Rank,Lat,Lon
0,0,35,Atlanta,Georgia,21.0,21.0,10.0,14.0,28.0,6.0,16,33.749099,-84.390185
1,1,43,Austin,Texas,15.0,12.0,19.0,19.5,4.0,8.5,8,30.271129,-97.743700
2,2,34,Baltimore,Maryland,13.0,19.0,9.0,16.0,24.5,21.5,17,39.290882,-76.610759
3,3,9,Birmingham,Alabama,34.0,34.0,34.0,34.0,34.0,22.5,42,33.520682,-86.802433
4,4,40,Boston,Massachusetts,24.0,14.0,8.0,6.0,24.5,6.0,11,42.360482,-71.059568
5,5,9,Buffalo,New York,34.0,34.0,34.0,34.0,34.0,22.5,42,42.886717,-78.878392
6,6,25,Charlotte,North Carolina,25.0,16.0,29.0,25.0,12.0,22.5,26,35.227087,-80.843127
7,7,47,Chicago,Illinois,2.0,3.0,4.0,4.0,33.0,3.0,4,41.875555,-87.624421
8,8,23,Cincinnati,Ohio,27.0,32.0,27.5,19.5,11.0,21.5,28,39.101454,-84.512460
9,9,27,Cleveland,Ohio,17.0,31.0,20.5,9.0,28.0,21.5,24,41.505161,-81.693445
10,10,29,Columbus,Ohio,11.5,18.0,31.0,24.0,17.0,21.5,22,39.962260,-83.000706
11,11,42,Dallas,Texas,11.5,9.0,18.0,11.0,9.0,21.5,9,32.776272,-96.796856
12,12,37,Denver,Colorado,16.0,15.0,12.0,13.0,21.0,12.0,14,39.739154,-104.984703
13,13,9,Detroit,Michigan,34.0,34.0,34.0,34.0,34.0,22.5,42,42.348664,-83.056737
14,14,9,Hartford,Connecticut,34.0,34.0,34.0,34.0,34.0,22.5,42,41.764549,-72.690867
15,15,49,Houston,Texas,3.0,4.0,6.0,5.0,10.0,12.0,2,29.758938,-95.367697
16,16,30,Indianapolis,Indiana,18.0,17.0,23.5,19.5,18.0,21.5,21,39.768333,-86.158350
17,17,9,Jacksonville,Florida,34.0,34.0,34.0,34.0,34.0,22.5,42,30.332184,-81.655651
18,18,25,Kansas City,Missouri,26.0,30.0,17.0,29.5,5.5,21.5,26,39.084469,-94.563030
19,19,9,Las Vegas,Nevada,34.0,34.0,34.0,34.0,34.0,22.5,42,36.166286,-115.149225
20,20,48,Los Angeles,California,6.0,2.0,2.0,2.0,31.0,4.0,3,34.054935,-118.244476
21,21,9,Louisville,Kentucky,34.0,34.0,34.0,34.0,34.0,22.5,42,38.254238,-85.759407
22,22,9,Memphis,Tennessee,34.0,34.0,34.0,34.0,34.0,22.5,42,35.149022,-90.051629
23,23,9,Miami,Florida,34.0,34.0,34.0,34.0,34.0,22.5,42,25.774266,-80.193659
24,24,32,Milwaukee,Wisconsin,7.0,29.0,25.5,23.0,16.0,8.5,19,43.034993,-87.922497
25,25,20,Minneapolis,Minnesota,29.0,28.0,23.5,26.0,19.0,21.5,31,44.977300,-93.265469
26,26,31,Nashville,Tennessee,23.0,22.0,14.0,19.5,13.0,22.5,20,36.162230,-86.774353
27,27,39,New Orleans,Louisiana,10.0,27.0,11.0,28.0,1.0,6.0,12,29.949932,-90.070116
28,28,50,New York,New York,1.0,1.0,1.0,1.0,32.0,1.0,1,40.730646,-73.986614
29,29,28,Oklahoma City,Oklahoma,28.0,23.0,15.5,33.0,3.0,21.5,23,35.472989,-97.517054
30,30,9,Orlando,Florida,34.0,34.0,34.0,34.0,34.0,22.5,42,28.542123,-81.379047
31,31,45,Philadelphia,Pennsylvania,4.0,5.0,3.0,3.0,28.0,12.0,6,39.952399,-75.163590
32,32,36,Phoenix,Arizona,20.0,10.0,22.0,10.0,7.0,21.5,15,33.448587,-112.077346
33,33,27,Pittsburgh,Pennsylvania,22.0,26.0,20.5,16.0,21.0,21.5,24,40.441694,-79.990086
34,34,33,Portland,Oregon,9.0,13.0,25.5,27.0,8.0,22.5,18,45.520247,-122.674195
35,35,9,Providence,Rhode Island,34.0,34.0,34.0,34.0,34.0,22.5,42,41.823989,-71.412834
36,36,9,Richmond,Virginia,34.0,34.0,34.0,34.0,34.0,22.5,42,37.538509,-77.434280
37,37,9,Riverside,California,34.0,34.0,34.0,34.0,34.0,22.5,42,33.953355,-117.396162
38,38,18,Rochester,New York,31.0,33.0,30.0,32.0,28.0,22.5,33,43.157285,-77.615214
39,39,9,Sacramento,California,34.0,34.0,34.0,34.0,34.0,22.5,42,38.581572,-121.494400
40,40,9,Salt Lake City,Utah,34.0,34.0,34.0,34.0,34.0,22.5,42,40.767013,-111.890431
41,41,41,San Antonio,Texas,8.0,8.0,13.0,16.0,14.5,21.5,10,29.424600,-98.495141
42,42,44,San Diego,California,19.0,7.0,7.0,7.5,5.5,12.0,7,32.717421,-117.162771
43,43,46,San Francisco,California,5.0,6.0,5.0,7.5,28.0,2.0,5,37.788337,-122.397445
44,44,22,San Jose,California,32.0,20.0,32.0,22.0,14.5,21.5,29,37.329709,-121.903160
45,45,38,Seattle,Washington,14.0,11.0,15.5,12.0,23.0,12.0,13,47.603832,-122.330062
46,46,9,St. Louis,Missouri,34.0,34.0,34.0,34.0,34.0,22.5,42,38.627273,-90.197889
47,47,19,Tampa,Florida,30.0,25.0,27.5,29.5,21.0,21.5,32,27.947759,-82.458444
48,48,21,Virginia Beach,Virginia,33.0,24.0,33.0,31.0,2.0,22.5,30,36.795303,-76.050925
49,49,9,Washington,District Of Columbia,34.0,34.0,34.0,34.0,34.0,22.5,42,38.894955,-77.036646

In [8]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import pandas as pd
import plotly
import plotly.plotly as py
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [ ]:
app = dash.Dash()

Top
available_indicators = ['Bar_Rank', 'Restaurant_Rank','Museums_Rank', 'Libraries_Rank','Park_Rank', 'TopRes_Rank']
app.layout = html.Div([
    html.Div([
        html.Div([
            dcc.Dropdown(
                id='First-care',
                options=[{'label': i, 'value': i} for i in available_indicators],
                #value = 'crime_rank'
            )
            ],
        style={'width': '48%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='Second-care',
                options=[{'label': i, 'value': i} for i in available_indicators],
                #value = 'hospital_rank'
            )
            ],
        style={'width': '48%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='Third-care',
                options=[{'label': i, 'value': i} for i in available_indicators],
                #value = 'hospital_rank'
            )
            ],
        style={'width': '48%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='Forth-care',
                options=[{'label': i, 'value': i} for i in available_indicators],
                #value = 'hospital_rank'
            )
            ],
        style={'width': '48%', 'display': 'inline-block'}),
        
        html.Div([
            dcc.Dropdown(
                id='Fifth-care',
                options=[{'label': i, 'value': i} for i in available_indicators],
                #value = 'hospital_rank'
            )
            ],
        style={'width': '48%', 'display': 'inline-block'}),
        
        
        html.Button('Submit', id='button'),
        
        html.Div(dcc.Graph(id='indicator-graphic'))
    ]),
    #dcc.Graph(id='indicator-graphic')
])

@app.callback(
    dash.dependencies.Output('indicator-graphic', 'figure'),
    [dash.dependencies.Input('button', 'n_clicks')],
    [dash.dependencies.State('First-care', 'value'),
     dash.dependencies.State('Second-care', 'value'),
     dash.dependencies.State('Third-care', 'value'),
     dash.dependencies.State('Forth-care', 'value'),
     dash.dependencies.State('Fifth-care', 'value')])
    
def update_graph(Button, First_care, Second_care, Third_care, Forth_care, Fifth_care):
    df = pd.DataFrame()
    df['City'] = Top['City']
    df['First'] = Top[First_care]
    df['Second'] = Top[Second_care]
    df['Third'] = Top[Third_care]
    df['Forth'] = Top[Forth_care]
    df['Fifth'] = Top[Fifth_care]
    df['Total'] = (df['First']*5+df['Second']*4+df['Third']*3+df['Forth']*2+df['Fifth']).rank(ascending=1)
    df['reverse_rank'] = df['Total'].rank(ascending=0)
    df['text'] = df['City'] + '<br># Final Rank ' + (df['Total']).astype(str)
    df['longitude'] = Top['Lon']
    df['latitude'] = Top['Lat']
    df = df.sort_values('Total', ascending = 1)
    
    limits = [(0,10),(10,20),(20,30),(30,40),(40,50)]
    colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)","rgb(255,133,27)","lightgrey"]
    cities = []


    for i in range(len(limits)):
        lim = limits[i]
        df_sub = df[lim[0]:lim[1]]
        city = dict(
            type = 'scattergeo',
            locationmode = 'USA-states',
            lon = df_sub['longitude'],
            lat = df_sub['latitude'],
            text = df_sub['text'],
            marker = dict(
                size = df_sub['reverse_rank']*10,
                color = colors[i],
                line = dict(width=0.5, color='rgb(40,40,40)'),
                sizemode = 'area'
            ),
            name = '{0} - {1}'.format(lim[0],lim[1]) )
        cities.append(city)

        layout = dict(
            title = 'The Entertainment-related ranking of US big cities',
            showlegend = True,
            geo = dict(
                scope='usa',
                projection=dict( type='albers usa' ),
                showland = True,
                landcolor = 'rgb(217, 217, 217)',
                subunitwidth=1,
                countrywidth=1,
                subunitcolor="rgb(255, 255, 255)",
                countrycolor="rgb(255, 255, 255)"
            ),
        )
        fig = dict( data=cities, layout=layout )
        
    return {   
        plotly.offline.plot( fig, validate=False )     
    }

app.run_server()

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Nov/2017 15:31:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2017 15:31:13] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2017 15:31:13] "GET /_dash-dependencies HTTP/1.1" 200 -
[2017-11-20 15:31:13,713] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda/lib/python3.6/site-packages/dash/dash.py", line 541, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/anaconda/lib/python3.6/site-packages/dash/dash.py", line 498, in add_context
    output_value = func(*args, **kwargs)
  File "<ipython-input-10-c83f9bfc106a>", line 72, in update_graph
    df['First'] = Top[First_care]
  File "/anaconda/lib/python3.6/site-packages/pandas/core/frame.py", line 2062, in __getitem__
    return self._getitem_column(key)
  File "/anaconda/lib/python3.6/site-packages/pandas/core/frame.py", line 2069, in _getitem_column
    return self._get_item_cache(key)
  File "/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1534, in _get_item_cache
    values = self._data.get(item)
  File "/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 3599, in get
    raise ValueError("cannot label index with a null key")
ValueError: cannot label index with a null key
127.0.0.1 - - [20/Nov/2017 15:31:13] "POST /_dash-update-component HTTP/1.1" 500 -
[2017-11-20 15:31:22,770] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda/lib/python3.6/site-packages/dash/dash.py", line 541, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/anaconda/lib/python3.6/site-packages/dash/dash.py", line 498, in add_context
    output_value = func(*args, **kwargs)
  File "<ipython-input-10-c83f9bfc106a>", line 75, in update_graph
    df['Forth'] = Top[Forth_care]
  File "/anaconda/lib/python3.6/site-packages/pandas/core/frame.py", line 2062, in __getitem__
    return self._getitem_column(key)
  File "/anaconda/lib/python3.6/site-packages/pandas/core/frame.py", line 2069, in _getitem_column
    return self._get_item_cache(key)
  File "/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1534, in _get_item_cache
    values = self._data.get(item)
  File "/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 3599, in get
    raise ValueError("cannot label index with a null key")
ValueError: cannot label index with a null key
127.0.0.1 - - [20/Nov/2017 15:31:22] "POST /_dash-update-component HTTP/1.1" 500 -